### ISSUE TITLE
Where is the source code for this project?

### ISSUE THREAD

**Issue by wolcen** [SimonJGillespie/AnjinVirtualComputer#2]
Could you please explain how Qemu is being included in your product? It would appear to have been integrated into your apk.

Qemu being licensed under the GPL, I would expect a derivative work such as this to provide source code when it is shared publicly.

I only see compiled software and documentation in this repository. What is the license of this project/where is the source repo?

Thank you!

**Comment by wolcen** [comment]
Actually, kernel-vexpress would probably be the actual qemu binary (the apk consisting of it's launcher/interface to the resulting VM having that VM structure defined in vexpress.dtb).

In any case - still curious about the project's license/possible source(s), and the source used for qemu in particular.

**Comment by SimonJGillespie** [comment]
Hi Chris,

Thanks for your interest. This is a sideline project in which I was lucky enough to have the time to upload a recent build of our system. Calling it a product is a bit of a stretch as I'm a single dev. 

The source code will be released at the appropriate moment and I'm happy to have a conversation with the Qemu developers who hold the license. If you represent them please let me know. 

These situations are by no means simple. They would want patches with a level of code quality that just isn't there right now. In time I hope that will be the case.  Given the number of downloads so far its not justifiable yet. Very early days. 

Just to be clear I have no problem sharing the source but it will need to be in consultation with the Qemu developers.

This forum is for questions about using the software and is not suitable for legal discussions. Could you confirm you have used the software please?

If you want to take the legal discussion further please follow me on twitter @anjin_games and we can DM.

**Comment by wolcen** [comment]
I do not represent Qemu, but am aware it is licensed under GPL v2. I also know they are a member of the [Software Freedom Conservancy](https://sfconservancy.org/) - I'm doubtful they would require any help from me. I approach you for selfish reasons: your project should have entitled me to the source of a Qemu derivative I could play with on a Quest 2 (given you have shared such a binary).

If you are unfamiliar with the GPL, please refer to the [license's FAQ](https://www.gnu.org/licenses/gpl-faq.html#ModifiedJustBinary)

For the record, you are not required to specifically notify Qemu of your changes, nor do you have to attempt to publish changes to that project. You are, however, required to share the source with anyone with whom you are sharing the binary (i.e. currently publicly). I had anticipated you would simply point me to the correct repository.

If you would like to keep the modified Qemu source private, you certainly have the right to do so, provided you are NOT distributing your changes in binary form.

Your apk can be licensed however you wish, of course (assuming that it is a not a derivative work).

At least, that is all my understanding as a free software developer - I am not providing legal advice. I recommend consulting a lawyer if you are unable to make sense of the licensing requirements on your own.
