### ISSUE TITLE
Cannot get networking to function

### ISSUE THREAD

**Issue by thaiwash** [SimonJGillespie/AnjinVirtualComputer#3]
Hi. Nice project btw. I couldn't get networking to function though. I edited the configuration file to my local router, 192.168.43.1, but still nothing, apt update not connecting to raspberrypi.org.

I was testing if it can run stuff like text editor, web browser, youtube. [YOU CAN"T DO ANY OF THIS WITHOUT NETWORKING, CLEARLY THIS IS A TROLL]
But, cant install window system without internet connection.
[YOU DIDN"T CHECK THE FAQ ITS PROBABLY THE DNS. NO INCLUDED LOGS/ERROR MESSAGES]

[HOBBY HORSE COMMENTS AND PROJECT INSULTS REMOVED]

[ADVERTISING YOU OWN PRODUCT AND USING OUR PROJECT TO DO IT, REMOVED]

[DO THIS AGAIN AND I WILL REPORT YOU TO GITHUB]

**Comment by SimonJGillespie** [comment]
Hi,

Not sure what to make of your email, its sort of rude, negative and
propping your own work and riding your own hobby horse. 4 things I dislike
intensely.

You say networking doesn't work but you have not mentioned any error
messages that are occurring for me to have any idea what is wrong. Most
likely your DNS isn't working and you haven't checked the FAQ which shows
how to use an external DNS (A common problem with Qemu)

Perhaps find another dev to wee on? I'm not up for that and unless you
adopt a better tone this is the last email you'll get from me. I don't
tolerate rude people.

It's a unique product that you don't understand and unless you have the
level of knowledge required you are just wasting your/my time.

Bye (I suspect for good)

Simon.

**Comment by SimonJGillespie** [comment]
User is clearly a troll- comment makes no sense claiming to use functionality that would be impossible to access. It was simply to promote their own projects.
